services:
  web:
    image: php:8.1-apache
    container_name: eseo_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./apache:/etc/apache2/sites-available
    restart: unless-stopped
